package com.telran.person.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.time.LocalDate;

@Entity // this annotation means that spring app needs to connect this Entity with a table in DB
public class Person {

    @Id // this field is an identifier of Entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // with this annotation id will be generated by DB
    //id of this table will be stored in the id table of DB
    private int id;

    private String name;
    private String lastName;
    private LocalDate birthday;

    public Person() {
    }

    public Person (String name, String lastName, LocalDate birthday){
        this.name = name;
        this.lastName = lastName;
        this.birthday = birthday;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getLastName() {
        return lastName;
    }

    public LocalDate getBirthday() {
        return birthday;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

}
